server:
  port: 18083
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 10MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:18080/eureka
  instance:
        lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
        lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
        prefer-ip-address: true
        ip-address: 127.0.0.1
        instance-id: ${spring.application.name}:${server.port}
fdfs:
  so-timeout: 1200
  connect-timeout: 600
  thumb-image:
    height: 60
    width: 60
  tracker-list:
    -127.0.0.1:22122
